boulder-food-rescue/food-rescue-robot

Gemfile
Gemfile.lock

`git://` uses `http` instead of `https`.
Also, this removes the warning when running `bundle install` :)

Change gem source from git:// to https://

---

Gemfile
Gemfile.lock

Was getting an error running `bundle exec rails console`.
```
activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
```

Add `test-unit` to Gemfile

---

app/models/log.rb

conv_weight was copy pasted from log_part in https://github.com/boulder-food-rescue/food-rescue-robot/commit/9f8c8e6495a3b29f6face03cb2b9a1fb3b799b19 and never defined. So changing to lp.weight.
conv_weight to lp.weight so its defined for conversion properly.

Changing to lp.weight so conv_weight doesn’t break. Poor copy/paste previously.

---

app/controllers/volunteers_controller.rb
spec/controllers/volunteers_controller_spec.rb

Begins fleshing out specs for actions of `volunteers_controller.spec`
- Specifically testing that instance variables are set, and that their values are as expected given various contexts.
- Sets the `#knight` action test to pending due to an existing 'undefined local variable or method `admin`'
- Corrects typo in `#unassigned` action, and replaces hash-rocket syntax

Adds detailed specs for VolunteersController#unassigned

---

config/locales/devise.en.yml

Fixes creative spelling of email in Devise message shown upon successful sign up

Correct typo in registration confirmation message

---

config/initializers/constant.rb

Rails already provides this method, and it takes an optional parameter so these implementations conflict. The only incompatibility could be that this implementation returned a Float instead of an Integer. I looked through the codebase for `sum` and I don't _think_ anything will be affected, but I'm not 100% sure.
@TimothyClayton also had to remove this, I think.
We should eventually move all these monkey patches on Array to a `Calculator` class or something.

Remove Array#sum monkey-patch

---

app/controllers/application_controller.rb
app/models/food_type.rb
app/models/scale_type.rb
app/views/schedule_chains/_form.html.erb

Some changes to reduce the number of custom scopes in models.
FoodType and ScaleType had `regional` scopes for specifying
a region_id during query. Instead, let's use the framework
and get those records using a ActiveRecord association.

Use Region associations over custom scopes

---

app/models/schedule.rb

Calling `volunteers` on a schedule will blow up - removing.

Remove unused association

---

app/models/volunteer.rb
spec/factories/absences.rb
spec/factories/log_volunteers.rb
spec/models/volunteer_spec.rb

Adds testing around the `Volunteer` model.
Converts `Volunteer::active` and `Volunteer::inactive` to use SQL instead of ruby.

Volunteer spec

---

app/models/schedule_chain.rb

I misread the implementation of `ScheduleChain#related_shifts` when
cleaning it up (commit a7ad7f1, PR #46).
Loading `/schedule_chains/:id` was blowing up...

Fix error introduced in commit a7ad7f1

---

spec/features/api_spec.rb

Should come back here at some point and look deeper into why these are failing, but it will be helpful for now to have CI passing so we can tell when changes break existing specs.

Temporarily skip API specs so that CI will pass

---

spec/factories/locations.rb
spec/factories/logs.rb
spec/factories/schedule_chains.rb
spec/factories/schedule_parts.rb
spec/factories/schedule_volunteers.rb
spec/factories/schedules.rb
spec/features/api_spec.rb
spec/lib/food_robot_spec.rb

The goal here is to be able to refactor the `#generate_log_entries` method. First step is to get a test case around everything so we don't lose functionality or break things since this a pretty core piece of functionality.
The test is slow, but hopefully we can remove it in favor of smaller, faster tests once the function is refactored.

Add spec for FoodRobot::generate_log_entries

---

app/controllers/locations_controller.rb
app/controllers/region_admin/donors_controller.rb
app/models/location.rb
app/views/layouts/application.html.erb
app/views/region_admin/donors/index.html.erb
config/routes.rb

Move `Location#donors` action out to an independent controller.
Motivations:
- reduce the size and complexity of `LocationsController`
- enforce authorization at controller level
- move to a `region_admin` namespace

Move donors index to separate controller

---

Gemfile
Gemfile.lock
spec/controllers/volunteers_controller_spec.rb
spec/factories/volunteers.rb
spec/features/volunteer_waiver_spec.rb
spec/rails_helper.rb
spec/support/login_helpers.rb

Replace controller specs around Volunteer waivers with integration specs.
- adds integration spec for viewing and signing waivers
- configure capybara with rspec test framework
- adds and configure  poltergeist for JS integration testing
Successor to #58

Replace waiver controller specs

---

Gemfile
Gemfile.lock
app/controllers/waivers_controller.rb
app/interactors/sign_waiver.rb
spec/interactors/sign_waiver_spec.rb

Service objects are helpful for cleaning up fat controllers and models (and decoupling the business logic from HTTP). The [`interactor` gem](https://github.com/collectiveidea/interactor) will provide a standard pattern for implementation of these service objects as opposed to using POROs which would be more likely to have varied interfaces.
I chose the "sign waiver" interaction to implement first because it's very simple (and is already covered by tests).

Add interactor gem and implement first interactor for signing the waiver

---

app/models/log.rb

The `Log::picked_up_by` query joins `:log_volunteers` which results in duplicate log objects for each assigned volunteer.
Solution is to use SQL DISTINCT to select distinct log records.

Fix duplicate logs being fetched for each assigned volunteer

---

app/controllers/logs_controller.rb

This fixes the error just sent out via email:
```
An ActiveRecord::StatementInvalid occurred in logs#export:
PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 1: … logs.when <= ‘2017-01-08’ AND complete AND region_id IN ())
^
: SELECT “logs".* FROM "logs” WHERE (logs.when >= ‘2017-01-04’ AND logs.when <= ‘2017-01-08’ AND complete AND region_id IN ())
```
Super admins have no `Assignment`s where `admin` is `true`. So `super_admin.admin_regions(true)` returns an empty array.
This PR changes `LogsController#export` to use the non-strict version of the function so that all regions are retrieved.

Fix export as super admin

---

app/controllers/logs_controller.rb
app/controllers/volunteers_controller.rb
app/models/log.rb
app/models/shift.rb
app/views/logs/index.html.erb
app/views/volunteers/home.html.erb

In a number of places, the app appears to be implicitly hinting at the concept of a "shift": a collection of logs belonging to the same schedule chain and occurring on the same date.
This PR adds a `Shift` model that is not backed by a SQL table, but encapsulates functionality related to a "shift".
I think `Shift` could eventually be a first-class Rails model, with its own SQL table, but there's a good deal of code that'd have to be refactored to get there. I think this PR is a good first step in that direction.

Extract Shift class to encapsulate logic around shifts

---

app/helpers/locations_helper.rb
app/views/locations/new.html.erb

For new locations, just show the plain header "New Location".  Don't try to display the location type.
Addressing this trello story -> https://trello.com/c/Ipjk8OSD/288-inconsistency-between-recipient-and-donor-controllers

Update form copy for new locations

---

app/models/log.rb

Fixes #74.
There was an issue where duplicate `log_volunteer` records were created when saving a `Log` with associated volunteers and `log_parts` created in memory. The problem only occurred in regions with exactly one scale type because the newly created logs are assigned that scale type.
We don't want to save the associated records individually as they depend on the `Log` record. We just set the attributes on them and let ActiveRecord save them itself.
---
I'd recommend we also remove all the duplicate records and add a uniqueness constraint on the DB. This SQL should delete all duplicate `log_volunteer` records, keeping the most recently created one:
```sql
WITH t AS (
SELECT id, rank() OVER (PARTITION BY volunteer_id, log_id ORDER BY created_at DESC) AS rank
FROM log_volunteers
) …
```

Only save associated log parts if they already exist in the database

---

app/views/notifier/schedule_collision_warning.html.erb

Schedule collision email was listing the first schedule location as both origin and destination.

Correct shift destination reference in schedule collision warning email

---

config/locales/devise.en.yml

Addresses Issue #79 
The devise .yml file contains a translation for `signed_up` that is intended to be presented when a user signs up for the site. But devise is looking for `signed_up_but_not_assigned`, and when a user signs up, they receive the message "translation missing" as documented in Issue #79. This PR provides the missing translation. The text is identical to the existing text for `signed_up`.

Added translation for signed_up_but_not_assigned.

---

app/models/region.rb

Both of these associations fail with errors:
`NameError: uninitialized constant Region::Donor` and `NameError: uninitialized constant Region::Recipient`
If they were being used anywhere, it would fail, so I feel comfortable just removing them.

[cleanup] Remove broken Region associations

---

app/models/log_part.rb

This PR addresses issue #86. LogPart#scale_weight is not used in the code and appears to be faulty on its face. Best course of action seems to be to delete the method.

Remove LogPart#scale_weight method

---

.rubocop_todo.yml
db/seeds.rb

I came across some trailing commas in `seeds.rb` that cause some unintended behavior.
These trailing commas result in an array being assigned to `assignment.volunteer_id` rather than separate values being assigned to `assignment.volunteer_id` and `assignment.region_id`.
```
> a = 1,
> b = 2,
=> [1, 2]
> a
=> [1, 2]
> b
=> 2
```

Remove trailing commas

---

circle.yml

Make sure we don't merge any code that breaks rubocop styles.

Add rubocop to circle ci build

---

spec/models/ability_spec.rb

The test has failed in the following circle ci builds:
- https://circleci.com/gh/boulder-food-rescue/food-rescue-robot/164
- https://circleci.com/gh/boulder-food-rescue/food-rescue-robot/180
- https://circleci.com/gh/boulder-food-rescue/food-rescue-robot/185
My hypothesis is that this flakiness is caused by the behavior of the logs factory when a region is not explicitly provided. The factory [picks a random region if at least 5 exist](https://github.com/boulder-food-rescue/food-rescue-robot/blob/ef/fix_flaky_ability_test/spec/factories/logs.rb#L5). That could occassionally pick the region that the volunteer is actually assigned to, making the test fail.
By assigning an explicitly different region to the log, my hope is that the test will no longer fail.

Fix flaky ability test

---

app/controllers/volunteers_controller.rb
app/interactors/toggle_super_admin.rb
spec/interactors/toggle_super_admin_spec.rb

This is intended to address Issue https://github.com/boulder-food-rescue/food-rescue-robot/issues/95

Issue 95: Interactors

---

.rubocop_todo.yml
lib/sample_data/region_data/admin_data.rb
lib/sample_data/region_data/donor_data.rb
lib/sample_data/region_data/recipient_data.rb
lib/sample_data/region_data/schedule_chain_data.rb
lib/sample_data/region_data/volunteer_data.rb

Provides more idiomatic `Array.new(number)` pattern instead of `number.times.map`.

Address `number.times.map` pattern violation

---

app/controllers/volunteers_controller.rb
app/interactors/reactivate_volunteer.rb
spec/interactors/reactivate_volunteer_spec.rb
spec/interactors/toggle_super_admin_spec.rb

Pull Volunteers#reactivate logic into an Interactor.
I developed an Authorize module that extends (monkey patches, 🙈) the Interactor module.  Good idea?  Bad idea?

Issue95 Interactor for Volunteers#reactivate

---

app/controllers/volunteers_controller.rb
app/models/log.rb
app/views/volunteers/home.html.erb
spec/features/shifts_needing_coverage_spec.rb

In response to #94 , this adds feature tests for volunteers viewing shifts that still need coverage. I also change the relevant instance variables set in the `volunteers#home` action and the nested conditionals in `Log.needing_coverage` for improved readability.
@rylanb

Add feature test for viewing shifts needing cov.

---

.codeclimate.yml

Single quotes in development.rb
Code climate is reporting a LOT of code duplicaton, so trying to up that threshold to avoid.
Docs: https://docs.codeclimate.com/docs/duplication

Updating ruby code climate threshold to 30.

---

app/controllers/volunteers_controller.rb
app/views/volunteers/home.html.erb
spec/factories/logs.rb
spec/features/region_admin/food_types/create_spec.rb
spec/features/region_admin/food_types/delete_spec.rb
spec/features/region_admin/food_types/index_spec.rb
spec/features/region_admin/food_types/update_spec.rb
spec/features/shifts_needing_coverage_spec.rb
spec/interactors/region_admin/create_food_type_spec.rb
spec/interactors/region_admin/delete_food_type_spec.rb
spec/interactors/region_admin/update_food_type_spec.rb

rand(3) will sometimes return 0 in the log factory.
Cleanup of home html code.
Occasionally the shifts_needing_coverage_spec.rb will fail based on logic for showing upcoming shifts.
def home in volunteers_controller.rb looks for `@shifts_needing_cov = Shift.build_shifts(Log.needing_coverage(current_volunteer.region_ids, 7, 10))` which would skip if recipients or donor was nil for a log.
Code cleanup added as well.

Fixing the shift coverage spec blinking failure. 

---

app/models/log_volunteer.rb
lib/de_dup_log_volunteers.rb
spec/lib/de_dup_log_volunteers_spec.rb
spec/models/log_volunteer_spec.rb

This is an alternative implementation of #80 that uses an ActiveRecord validation instead of a SQL unique index to prevent duplicate `log_volunteers` records. The SQL unique index was not an option because it couldn't be adequately represented in `schema.rb`.

De-dup log_volunteers

---

app/assets/stylesheets/base/_headers.scss
app/assets/stylesheets/modules/_buttons.scss
app/controllers/logs_controller.rb
app/controllers/volunteers_controller.rb
app/models/food_type.rb
app/models/region.rb
app/models/shift.rb
app/models/volunteer.rb
app/views/logs/_form.html.erb
app/views/logs/edit.html.erb
app/views/volunteers/shift_stats.html.erb
app/views/volunteers/stats.html.erb
config/initializers/query_troubleshooting.rb
config/routes.rb

The BFR Volunteer Coordinator would like to see top # of shifts for volunteers by region all time.
When going to volunteer stats you can now to go shift stats from that page to see top # of completed shifts all time.
This includes code/html/space cleanup and optimizations for lookups of regions site wide. The nav was calling functions that did individual region lookups. I updated shift.rb to add an eager load method to grab logs and schedule chains and THEN build shifts. This prevents multiple hits to schedule chains table .
I tested it and locally 11-12 seconds initially w/o eager loading of schedule chains and 7.3s after.

Shift Volunteer stats views updates

---

.rubocop_todo.yml
app/controllers/absences_controller.rb
app/controllers/locations_controller.rb
app/controllers/logs_controller.rb
app/controllers/schedule_chains_controller.rb
app/controllers/volunteers_controller.rb
app/models/location.rb
spec/controllers/assignments_controller_spec.rb
spec/controllers/cell_carriers_controller_spec.rb
spec/controllers/regions_controller_spec.rb
spec/controllers/scale_types_controller.rb
spec/controllers/schedule_chains_controller_spec.rb
spec/controllers/sessions_controller_spec.rb
spec/controllers/transport_types_controller_spec.rb
spec/controllers/waivers_controller_spec.rb
spec/models/location_spec.rb

First PR to help—tackled some low-hanging rubocop fruit. Caught a small validation bug with that rule.
- Fixed Rubocop whitespace issues that were not ignored
- Fixed only instance of same variable comparison, which fixed a broken validation
- Added sentence version of errors to all flash messages. May not be the prettiest, but will help the user / dev figure out what happened.

Chore / Removed a Rubocop TODO, improved flash errors

---

lib/tasks/sample_data.rake

`generate_log_entries` is not a thing. We want to refer to https://github.com/boulder-food-rescue/food-rescue-robot/blob/ef/fix_task_name/lib/tasks/foodrobot.rake#L5

Fix name of task to generate logs in rake sample_region output

---

app/models/schedule_chain.rb

`covered?` returns true only for chains that are entirely full

Correct comment- definition of #covered? has changed

---

app/controllers/volunteers_controller.rb
app/models/volunteer.rb
spec/features/region_admin/shiftless_volunteers_spec.rb
spec/models/volunteer_spec.rb

Addresses #130 -- Previously, the shiftless volunteers route was loading all volunteers
into memory and performing n<sup>2</sup>+1 database queries to figure
out which ones in the shared regions have no shifts assigned. This was
translated into equivalent SQL
I thought a count subquery was simpler than an equivalent left join / group / having
There remains the question as to whether `current_volunteer.region_ids`
is a decent criteria for finding shiftless volunteers. Another option
might be `current_volunteer.admin_region_ids` ?

Shiftless Volunteers query perf + integration test

---

.rubocop.yml
app/controllers/logs_controller.rb
app/controllers/volunteers_controller.rb
app/helpers/volunteers_helper.rb
app/views/absences/_form.html.erb
app/views/locations/index.html.erb
app/views/volunteers/region_admin.html.erb
spec/controllers/volunteers_controller_spec.rb

Avoid Volunteer.all calls from certain dropdown builds and fixes a few other errors I ran across. Rebase of #149

Remove volunteer all calls

---

lib/tasks/foodrobot.rake

This is slightly cleaner code, but it is not ideal overall.
Trello Feature request: generate logs for unclaimed schedule items 8 days in advance.
The logs auto-generate 5 days in advance right now and region/volunteer coordinators would like it to be 8 days in advance.
To not do it this way would require a large refactor. So duct tape and bubblegum it is!

Updating to generate logs 8 days in advance.

---

README.md
bin/setup

The setup for Linux / Mac specified in the ReadMe did not work on my Mac computer nor my classmate's Mac computer. There were two issues we ran into:
1. The secret key was not generated automatically in the `.env` file.
2. The test database was not created when running the the bin/setup file.
I added a line to the ReadMe that states you must generate the rake secret key manually.
I also added two lines to the `bin/setup` file which creates a test database and loads the schema. This monkey patch doesn't actually address why the `bootstrap.db` is not generating a test database.
When the `.env` file sets up the test environment database, it hits an error saying it has already been created:
However, when checking the my databases in psql, I only see a "bfr_webapp_db" and not the associated …

Add rake commands to create and migrate test database.

---

app/controllers/schedule_chains_controller.rb
app/interactors/create_schedule_chain.rb
app/views/schedule_chains/_form.html.erb
app/views/schedule_chains/index.html.erb
app/views/schedule_chains/show.html.erb
spec/interactors/create_schedule_chain_spec.rb

Resolves #163 by reusing some LogGenerator services to create rescue logs for one-time, same day schedules when they are created.
Normally, a daily task (foodrobot:generate_logs) would generate all the logs from the schedule, but often this would happen too late for schedules created on the same day.

Generate rescue log if new schedule is one-time, same day

---

README.md

`bin/setup` didn't work for me without `bundle exec`, and the error was cryptic.

update docs based on what I ran into setting things up

---

app/models/location.rb

Location.rb had some bugs in it based on a refactor causing generated logs to fail. 
Bug fixes in master: 
https://github.com/boulder-food-rescue/food-rescue-robot/commit/abefee6e3dcc11ba4ac1651bc6b454cc0bea767e
This branch has follow-up cleanup.
I found that you can do this too: 
```
def day_length(index)
hours_on_day(index).reverse.reduce(:-)
end
```
to fix the initial bug from refactor.
Any thoughts?

Slight clean-up to detailed_hours validation 
