boulder-food-rescue/food-rescue-robot

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds basic structure for submitting PRs and Issues.
- Wanted to add some default behavior and structure for creating PRs
and/or issues.
- Helpful documentation is commented so they don't show up as noise
when submitting.
- Sections that aren't desired can be easily deleted when prepping to
submit new work.
=> Added GitHub templates for pull requests and issues.

app/controllers/logs_controller.rb, app/views/logs/_form.html.erb, app/views/logs/_take_or_leave.html.erb, app/views/logs/index.html.erb
Logs controller and the views had unnecessarily complex code. Painful
Cleaned up to use rails helpers for link_to / removed inline JavaScript. 
Cleaned up def take method in logs controller.
=> Logs Controller / Views cleanup.

app/views/schedule_chains/_form.html.erb, config/initializers/constant.rb
=> Replace DayOfWeek initializer constant

app/models/region.rb, config/environments/test.rb, spec/factories/locations.rb, spec/factories/schedule_chains.rb, spec/models/region_spec.rb
`Region` class needs some unit testing.
Following commits in order, you'll see each method get tested and refactored.
Last commit updates the test logger to omit SQL/DB output  If bad feels, we can remove that commit.
=> Region unit spec

Gemfile, Gemfile.lock
The test database uses sqlite. I think this gem is a dependency.
=> Add `sqlite3` to Gemfile

app/models/food_type.rb, spec/models/food_type_spec.rb
Code clean up on `FoodType`, add blank spec
=> Clean up FoodType

app/controllers/regions_controller.rb, app/views/regions/index.html.erb
Clean up and refactor parts of the `RegionController`
Clean up Region#Index view
=> Region controller cleanup

app/controllers/locations_controller.rb, app/models/location.rb, app/models/region.rb, app/models/schedule.rb, app/models/schedule_chain.rb, app/views/layouts/custom_devise.html.erb, app/views/locations/_form.html.erb, spec/models/location_spec.rb
Adds unit testing around some of `Location` + refactoring + code clean up.
=> Location spec

app/views/layouts/custom_devise.html.erb
=> Update repo URL on session#new

app/models/log.rb, app/views/layouts/custom_devise.html.erb
Clean up AR queries for `session#new`
=> Session#new AR queries

app/models/volunteer.rb
Cleans up code formatting to make the code more readable and maintainable.
Intended to have exactly the same functionality as before.
=> Clean up Volunteer model

app/models/location.rb, spec/factories/locations.rb, spec/factories/logs.rb
Fixes factories for `Location` and `Log` models.
=> Factory fixes

.gitignore, app/models/assignment.rb, spec/controllers/volunteers_controller_spec.rb
Fills out `#assign` action specs for VolunteersController
=> Added more detailed specs for VolunteersController#assign

config/application.rb
- turn off assets, helper, stylesheets
- configure with rspec test framework
=> Add application generator configuration

app/helpers/assignments_helper.rb, app/helpers/cell_carriers_helper.rb, app/helpers/food_types_helper.rb, app/helpers/logs_helper.rb, app/helpers/schedules_helper.rb, app/helpers/test_helper.rb, app/helpers/transport_types_helper.rb
=> Remove unused helpers

app/controllers/volunteers_controller.rb, app/models/schedule_chain.rb, app/views/schedule_chains/_form.html.erb, app/views/schedule_chains/show.html.erb
Makes code easier to understand and maintain.
=> Schedule chain cleanup

app/models/log.rb, lib/food_robot.rb, lib/food_robot/log_generator.rb, lib/food_robot/log_generator/existing_logs.rb, lib/food_robot/log_generator/log_builder.rb, lib/food_robot/log_generator/schedule_chain_decorator.rb
Should make log generation process easier to understand, maintain, and modify.
=> Decompose FoodRobot::generate_log_entries by pulling out some classes

spec/factories/volunteers.rb, spec/features/region_admin/donors_spec.rb, spec/features/volunteer_waiver_spec.rb
Add integration spec around new `/region_admin/donors` index.  
Spec for commit #53
=> Donors integration spec

app/controllers/volunteers_controller.rb, app/presenters/volunteer_stats_presenter.rb, app/presenters/volunteer_stats_presenter/lbs_by_month_graph_presenter.rb, app/presenters/volunteer_stats_presenter/pickup_stats_presenter.rb, app/views/volunteers/_food_by_month.html.erb, app/views/volunteers/_pickup_stats.html.erb, app/views/volunteers/home.html.erb
Extracts complex view logic from `volunteers_controller#home`.
=> Add presenter for volunteer stats

app/controllers/scale_types_controller.rb, app/views/locations/hud.html.erb, app/views/locations/index.html.erb, app/views/region_admin/donors/index.html.erb, config/routes.rb, spec/support/authenticated_index.rb
These fell out of [my work on implementing authorization with Pundit](https://github.com/boulder-food-rescue/food-rescue-robot/pull/69#issuecomment-271917223) and can be merged separately.
=> Some assorted cleanup commits

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/food_types_controller.rb, app/controllers/locations_controller.rb, app/controllers/logs_controller.rb, app/controllers/regions_controller.rb, app/controllers/scale_types_controller.rb, app/models/ability.rb, spec/models/ability_spec.rb
There's a lot of duplicated logic for permissions-checking scattered across the app. [CanCan](https://github.com/CanCanCommunity/cancancan) will help centralize our permissions logic.
- This is a first step. Future PRs can replace more permissions code with `authorize!` or other `CanCan` methods.
- This PR also standardizes the behavior of the application when a user tries to do something that they're not authorized for to always display a flash message and redirect back (or to `root_path` if no referrer is available).
=> Introduce 'cancancan' gem for authorization

lib/food_robot/log_generator.rb
Fixes noisy suite:
```bash
‡ be rspec spec/
Randomized with seed 33534
.................................................................*.............................................*********Schedule Chain: D1291 -> R1292 -> D1293 -> R1294
.Schedule Chain: D1295 -> R1296 -> D1297 -> R1298
.Schedule Chain: D1299 -> R1300 -> D1301 -> R1302
.Schedule Chain: D1303 -> R1304 -> D1305 -> R1306
.Schedule Chain: D1307 -> R1308 -> D1309 -> R1310
.Schedule Chain: D1311 -> R1312 -> D1313 -> R1314
.Schedule Chain: D1315 -> R1316 -> D1317 -> R1318
.Schedule Chain: D1319 -> R1320 -> D1321 -> R1322
..Schedule Chain: D1326 -> D1327 -> R1328
.Schedule Chain: D1329 -> D1330 -> R1331
.Schedule Chain: D1332 -> D1333 -> R1334
.Schedule Chain: D1335 -> D1336 -> R1337
.Schedule Chain: D1339 -> D1340 -> R1341 …
```
=> Replace `puts` with `Rails.logger`

README.md
The sample database config does not match the README.
=> [DOCS] Update readme to match database.yml.dist

Gemfile.lock, app/controllers/assignments_controller.rb
Because single letter variable names are difficult to follow
Change R to region
Change V to volunteer
Change A to assignment
=> Change r to region v to volunteer and a to assignment

Makefile, README.md
We could be more clear on the ways to set this up
Hopefully, very straightforward setup with step-by-step instructions.
=> Updating Readme for setup fixes from tmikeschu

app/controllers/locations_controller.rb
locations_controller
Change @loc to @location in #hud		
Change @loc to @location in #show		
Change @l to @location in #destroy
=> Refactor locations controller

app/controllers/food_types_controller.rb
Simply change variable @l to food_type in #destroy
=> Change @l to food_type in #destroy

app/controllers/locations_controller.rb, app/controllers/logs_controller.rb
Refactor logs_controller
Change d to date in #by_day
Change t to total in #stats_service
Change l to log_part, change w to word
Change @l to @log in #destroy
Change @l to location in #destroy
Change l to logs, l to log and lv to log_volunteer in #leave
Change @loc to @location in #take
Change lg to log_part in #parse_and_create_log_part
Change lp to log_part in #finalize_log
=> Refactor logs controller

Gemfile, Gemfile.lock, spec/rails_helper.rb
https://github.com/mattheworiordan/capybara-screenshot
=> Add capybara-screenshot gem to take screenshots of failed feature specs

spec/models/absence_spec.rb, spec/models/assignment_spec.rb, spec/models/cell_carrier_spec.rb, spec/models/log_part_spec.rb, spec/models/log_recipient_spec.rb, spec/models/log_spec.rb, spec/models/log_volunteer_spec.rb, spec/models/scale_type_spec.rb, spec/models/schedule_chain_spec.rb, spec/models/schedule_part_spec.rb, spec/models/schedule_spec.rb, spec/models/schedule_volunteer_spec.rb, spec/models/shift_spec.rb, spec/models/transport_type_spec.rb
All model specs exist
Any new file has one test test validating a `super_admin`, and is stubbed out so it shows as `pending`
=> All Models now have specs

spec/controllers/assignments_controller_spec.rb, spec/controllers/cell_carriers_controller_spec.rb, spec/controllers/regions_controller_spec.rb, spec/controllers/scale_types_controller.rb, spec/controllers/schedule_chains_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/transport_types_controller_spec.rb, spec/controllers/waivers_controller_spec.rb
Setup controller specs to output message that they need to be written when running suite
added controller specs for each controller except application controller
=> Adding controller test placeholders

app/controllers/volunteers_controller.rb, app/views/volunteers/_form.html.erb, app/views/volunteers/new.html.erb, app/views/volunteers/show.html.erb
Cleaner HTML / hash syntax in volunteers/_form and /new/show
Updates to fix misspellings / missed variable renames in Vido’s branch.
=> Cleaning up all kinds of code! Yay Vido!

app/controllers/schedule_chains_controller.rb, app/models/ability.rb
Adds CanCanCan auth to ScheduleChains. See #96.
=> Implement CanCanCan auth for ScheduleChains

app/assets/javascripts/application.js, app/assets/javascripts/global.js, app/assets/stylesheets/modules/_tables.scss, app/views/absences/_form.html.erb, app/views/absences/edit.html.erb, app/views/absences/index.html.erb, app/views/absences/new.html.erb, app/views/locations/hud.html.erb, app/views/locations/index.html.erb, app/views/logs/index.html.erb, app/views/region_admin/donors/index.html.erb, app/views/region_admin/food_types/index.html.erb, app/views/regions/index.html.erb, app/views/scale_types/index.html.erb, app/views/schedule_chains/_form.html.erb, app/views/schedule_chains/index.html.erb, app/views/volunteers/index.html.erb, app/views/volunteers/stats.html.erb, app/views/volunteers/unassigned.html.erb
Because the code could use some clean-up and visually could look better.
- $('#data_table').dataTable({}) moved into a global.js file
- Adding some visual improvements to the dataTables search section. Making more consistent.
- Indentation and HTML code clean-up
- Ruby clean-up of code for better readability / efficiencies
=> Code Clean-up :: Development -> Master

.rubocop_todo.yml, .travis.yml, app/controllers/logs_controller.rb, app/controllers/volunteers_controller.rb, app/models/log_volunteer.rb, app/models/volunteer.rb, app/views/volunteers/_form.html.erb
Would like to have CI running for Pull Requests to find issues properly in advance.
Adding .travis.yml file.
https://docs.travis-ci.com/user/customizing-the-build
=> Travis CI Setup

app/assets/javascripts/datepicker_footer.js, app/assets/javascripts/datepicker_head.js, app/models/location.rb, app/views/volunteers/_datepicker.html.erb, app/views/volunteers/region_admin.html.erb
Brandon Baker did great work on adding an AirBnB styled datepicker to prevent invalid dates from being selected in the region admin. I had to make some updates to clean things up slightly so that it worked in production (yay compiled assets!)
=> Datepicker Updates for production
